project:
  type: website
  output-dir: docs

website:
  title: "{SET}grp"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - people.qmd
      - text: "Software"
        menu: 
          - text: "NRTAPmodel"
            href: https://spatiotemporal-exposures-and-toxicology.github.io/NRTAPmodel/
          - text: "GeoTox" 
            href: https://spatiotemporal-exposures-and-toxicology.github.io/GeoToxPackage/
      - teaching.qmd
    logo: images/setlogo.jpg

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

