project:
  type: website
  output-dir: docs

website:
  title: "{SET}grp"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - people.qmd
      - teaching.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

