project:
  type: website
  output-dir: .

website:
  title: "{SET}grp"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "People"
        menu:
          - text: "Kyle P Messier"
            href: people.html#KPM
          - text: "Mariana Alifa"
            href: people.html#MAK
          - text: "Ranadeep Daw"
            href: people.html#RD
          - text: "Eva Marques"
            href: people.html#ESM
          - text: "Insang Song"
            href: people.html#IS
          - text: "Daniel Zilber"
            href: people.html#DZ
          - text: "Mitchell Manware"
            href: people.html#MM
          - text: "Former Members"
            href: people.html#FormerMembers            
      - text: "Software"
        menu: 
          - text: "beethoven"
            href: https://spatiotemporal-exposures-and-toxicology.github.io/beethoven/
          - text: "GeoTox" 
            href: https://spatiotemporal-exposures-and-toxicology.github.io/GeoTox/
      - text: "Presentations"
        menu: 
          - text: "NIMHD-2024-01-09"
            href: presentations/nimhd-2024-01-09.pdf
          - text: "SOT-ISES-Webiinar-2024-02-14"
            href: presentations/KPM_SOT_ISES_Webinar_20240214.html            
    logo: images/setlogo.jpg

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

